# Generated by Django 4.0.4 on 2023-01-18 15:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessuser',
            name='subscription',
        ),
        migrations.AddField(
            model_name='businessuser',
            name='creditCardCode',
            field=models.CharField(default='1111', max_length=4),
        ),
        migrations.AddField(
            model_name='businessuser',
            name='creditCardExpirationDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='businessuser',
            name='creditCardNumber',
            field=models.CharField(default='1111', max_length=30),
        ),
        migrations.AddField(
            model_name='businessuser',
            name='startSubscriptionDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
