# Generated by Django 4.0.4 on 2023-01-18 19:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_businessuser_creditcardexpirationdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessuser',
            name='startSubscriptionDate',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
