# Generated by Django 4.0.4 on 2023-01-18 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_businessuser_startsubscriptiondate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessuser',
            name='creditCardCode',
            field=models.CharField(default='1111', max_length=8),
        ),
        migrations.AlterField(
            model_name='businessuser',
            name='creditCardExpirationDate',
            field=models.CharField(max_length=10),
        ),
    ]
