# Generated by Django 4.0.4 on 2023-01-18 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formularz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=100)),
                ('opis', models.CharField(max_length=500)),
                ('hasloDostepu', models.CharField(blank=True, max_length=30, null=True)),
                ('czyAktywny', models.BooleanField()),
                ('owner', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Badanie',
            fields=[
                ('formularz_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.formularz')),
            ],
            bases=('base.formularz',),
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('formularz_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.formularz')),
                ('pokazWynik', models.BooleanField()),
                ('pokazPoprawne', models.BooleanField()),
                ('czasTrwania', models.IntegerField()),
                ('terminOtwarcia', models.DateTimeField()),
                ('terminZamkniecia', models.DateTimeField()),
            ],
            bases=('base.formularz',),
        ),
        migrations.CreateModel(
            name='Rozwiazanie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ktoRozwiazal', models.CharField(blank=True, max_length=254, null=True)),
                ('odpowiedz', models.CharField(max_length=1000)),
                ('numerPytania', models.IntegerField()),
                ('formularz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.formularz')),
            ],
        ),
        migrations.CreateModel(
            name='Pytanie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numer', models.IntegerField()),
                ('tresc', models.CharField(max_length=300)),
                ('zamkniete', models.BooleanField()),
                ('formularz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.formularz')),
            ],
        ),
        migrations.CreateModel(
            name='Odpowiedz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tresc', models.CharField(max_length=300)),
                ('czyPoprawna', models.BooleanField()),
                ('pytanie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.pytanie')),
            ],
        ),
    ]
