# Generated by Django 4.0.4 on 2023-01-18 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rozwiazanie',
            name='numerPytania',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.pytanie'),
        ),
    ]
