# Generated by Django 4.0.4 on 2023-01-18 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_rozwiazanie_numerpytania'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rozwiazanie',
            old_name='numerPytania',
            new_name='pytanie',
        ),
    ]
