# Generated by Django 4.0.4 on 2023-01-18 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_numerpytania_rozwiazanie_pytanie'),
    ]

    operations = [
        migrations.AddField(
            model_name='formularz',
            name='isPublic',
            field=models.BooleanField(default=True),
        ),
    ]
