# Generated by Django 4.0.4 on 2023-01-19 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_formularz_ispublic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formularz',
            name='czyAktywny',
            field=models.BooleanField(default=False),
        ),
    ]
