# Generated by Django 4.0.4 on 2023-01-19 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_formularz_czyaktywny'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='pokazPoprawne',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='pokazWynik',
            field=models.BooleanField(default=True),
        ),
    ]
